urls.py
from django.conf.urls.defaults import patterns , url
from djangoweb.sharehp import views
from djangoweb.sharehp import bops_views
from djangoweb.sharehp.views import require_login
from djangoweb.sharehp.bops_views import require_admin

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^index/$', views.index),

    url(r'^tag/(video|image)/$', views.classify),

    url(r'^detail/(video|image)/(\d+)/$', views.detail),
    url(r'^detail/(video|image)/(\d+)/(next|prev)/$', views.another),

    url(r'^new_resource/$', require_login(views.new_resource)),

    url(r'^register/$', views.register),
    url(r'^login/$', views.login),
    url(r'^loginout/$', views.loginout),

    url(r'^groups/$', views.groups),
    url(r'^group/(\d+)/$', views.group, {'order': 'default'}),
    # url(r'^group/(\d+)/(hot)/$', views.group),
    url(r'^group/(\d+)/new_topic/$', require_login(views.new_topic)),
    url(r'^group/topic/(\d+)/$', views.group_topic),

    url(r'^account/change_avatar/$', require_login(views.change_avatar)),
    url(r'^account/change_password/$', require_login(views.change_password)),

    url(r'user/(\d+)', views.user_info),

    url(r'^api/add_new_resource/$', views.add_new_resource),
    url(r'^api/group/(\d+)/add_new_topic/$', views.add_new_topic),
    url(r'^api/group/topic/(\d+)/add_new_comment/$', views.add_topic_comment),
    url(r'^api/upload_image/$', views.upload_image),
    url(r'^api/upload_video/$', views.upload_video),
    url(r'^api/detail/(\d+)/add_new_comment/$', views.add_resource_comment),
    url(r'^api/resource_vote/(\d+)/(up|down)/$', views.resource_vote),

    url(r'^bops/tag/$', require_admin(bops_views.classify)),
    url(r'^bops/detail/(\d+)/$', require_admin(bops_views.detail)),
    url(r'^bops/resource/(\d+)/(pass|reject)/$', bops_views.process),
)

sharehp/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
class User(models.Model):
    gmt_create = models.DateTimeField()
    gmt_modify = models.DateTimeField()
    email = models.CharField(max_length=128)
    nickname = models.CharField(max_length=32)
    password = models.CharField(max_length=32)
    avatar = models.CharField(max_length=1024)  # jsonstr
    status = models.CharField(max_length=32)


class Resource(models.Model):
    gmt_create = models.DateTimeField()
    gmt_modify = models.DateTimeField()
    user_id = models.IntegerField()
    # 资源标题
    title = models.CharField(max_length=10240)
    type = models.CharField(max_length=32)
    # 资源缩略图 {'url': ..., 'size': ...}
    thumbnail = models.CharField(max_length=255)
    # 资源内容 {'url': ..., 'size': ...}
    content = models.CharField(max_length=10240)
    up = models.IntegerField()
    down = models.IntegerField()
    comments = models.IntegerField()
    status = models.CharField(max_length=32)


class Resource_Comment(models.Model):
    gmt_create = models.DateTimeField()
    gmt_modify = models.DateTimeField()
    res_id = models.IntegerField()
    user_id = models.IntegerField()
    # 评论内容 plain text
    content = models.CharField(max_length=10240)
    have_reply = models.CharField(max_length=1)
    status = models.CharField(max_length=32)


class Group(models.Model):
    gmt_create = models.DateTimeField()
    gmt_modify = models.DateTimeField()
    group_name = models.CharField(max_length=256)
    group_desc = models.CharField(max_length=512)
    avatar = models.CharField(max_length=1024)  # jsonstr
    # status = models.CharField(max_length=16)


class Group_Topic(models.Model):
    gmt_create = models.DateTimeField()
    gmt_modify = models.DateTimeField()
    group_id = models.IntegerField()
    user_id = models.IntegerField()
    topic_name = models.CharField(max_length=256)
    comments = models.IntegerField()
    status = models.CharField(max_length=16)


class Topic_Comment(models.Model):
    gmt_create = models.DateTimeField()
    gmt_modify = models.DateTimeField()
    user_id = models.IntegerField()
    topic_id = models.IntegerField()
    # 话题内容
    content = models.CharField(max_length=10240)
    # 附件
    # {'attachment': {'type': ...,
    #                'size': ...,
    #                'url':...,
    #                'exist': ...},
    attachment = models.CharField(max_length=1024)
    status = models.CharField(max_length=16)


#  爬取资源
class Spide_Resource(models.Model):
    gmt_create = models.DateTimeField()
    title = models.CharField(max_length=1024)
    type = models.CharField(max_length=32)
    # 资源内容
    # {
    #   'thumbnail_path': ..., 缩略图路径
    #   'normal_path': ...,  原始图片路径(video unused)
    #   'url': ... 视频swf(image unused)
    # }
    content = models.CharField(max_length=1024)
    # 爬取资源的原始url
    origin = models.CharField(max_length=1024)
    # 原始url的md5值（防止重复爬取）
    md5 = models.CharField(max_length=256)
    status = models.CharField(max_length=32)

sharehp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import User
from utils import common

# 注册表单
class RegisterForm(forms.Form):
    email = forms.EmailField(max_length=128,
                             error_messages={'required': u'请输入邮箱', 'invalid': u'邮箱格式不正确', 'max_length': u'邮箱太长了哎'})
    nickname = forms.CharField(min_length=4, max_length=16,
                               error_messages={'required': u'请输入昵称', 'min_length': u'昵称长度太短了（至少四个字符）',
                                               'max_length': u'昵称太长了哎'})
    password = forms.CharField(min_length=6, max_length=16,
                               error_messages={'required': u'请输入密码', 'min_length': u'密码长度太短了（至少六位）',
                                               'max_length': u'密码太长了哎'})

    def clean_email(self):
        email = self.cleaned_data['email'].strip()
        is_exist = User.objects.filter(email=email).exists()
        if is_exist:
            raise forms.ValidationError(u'邮箱已经被注册！')
        return email

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname'].strip()
        is_exist = User.objects.filter(nickname=nickname).exists()
        if is_exist:
            raise forms.ValidationError(u'昵称已经被占用, 换一个吧！')
        return nickname


# 登录表单
class LoginForm(forms.Form):
    email = forms.EmailField(max_length=128,
                             error_messages={'required': u'请输入邮箱', 'invalid': u'邮箱格式不正确', 'max_length': u'邮箱太长了哎'})
    password = forms.CharField(max_length=16, error_messages={'required': u'请输入密码', 'max_length': u'密码太长了哎'})

    def clean_email(self):
        email = self.cleaned_data['email'].strip()
        is_exist = User.objects.filter(email=email).exists()
        if not is_exist:
            raise forms.ValidationError(u'邮箱还没有注册哦！')
        return email

    def clean(self):
        cleaned_data = self.cleaned_data
        email = cleaned_data.get("email", '')
        password = cleaned_data.get("password", '')
        if password and email:
            is_exist = User.objects.filter(email=email.strip(),
                                           password=common.encode_password(password).strip()).exists()
            if not is_exist:
                raise forms.ValidationError(u"密码错误！")
        return cleaned_data


# 修改密码
class ChangePasswordForm(forms.Form):
    password = forms.CharField(max_length=16, error_messages={'required': u'请输入旧密码', 'max_length': u'密码太长了哎'})
    new_password = forms.CharField(max_length=16, error_messages={'required': u'请输入新密码', 'max_length': u'密码太长了哎'})
    confirm_password = forms.CharField(max_length=16, error_messages={'required': u'请再次输入新密码', 'max_length': u'密码太长了哎'})

    def clean(self):
        cleaned_data = self.cleaned_data
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if confirm_password and new_password:
            if not (confirm_password == new_password):
                raise forms.ValidationError(u"两次输入密码不一致！")
        return cleaned_data

sharehp/templates/change_password.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/sharehp/css/sharehp.css" rel="stylesheet">
</head>
<body>
{% include "header.htm" %}
<div class="container">
    <div class="row">
        <div class="span8">
            <div class="background-wall">
                {% if success %}
                    <div class="alert alert-success">
                        <h5>修改密码成功!</h5>
                    </div>
                {% else %}
                    <div class="form-change-password">
                        <form action="/account/change_password/" method="post">
                            <span class="error">{{ form.non_field_errors }}</span>
                            <span class="error">{{ form.password.errors }}</span>
                            <input id="id_password" name="password" type="password" class="input-block-level"
                                   placeholder="旧密码" value="{{ form.password.value }}">
                            <span class="error">{{ form.new_password.errors }}</span>
                            <input id="id_new_password" name="new_password" type="password" class="input-block-level"
                                   placeholder="新密码" value="{{ form.new_password.value }}">
                            <span class="error">{{ form.confirm_password.errors }}</span>
                            <input id="id_confirm_password" name="confirm_password" type="password"
                                   class="input-block-level"
                                   placeholder="确认新密码" value="{{ form.confrim_password.value }}">
                            <button class="btn input-block-level btn-primary" type="submit">确定</button>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="span4">
            <div class="background-wall">
                <ul class="nav nav-pills nav-stacked">
                    <li>
                        <a href="/account/change_avatar/">我的头像</a>
                    </li>
                    <li class="active">
                        <a href="/account/change_password/">修改密码</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <br>
    <br>
    <br>
    <br>
</div>
<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</body>
</html>

sharehp/templates/detail.htm
{% load poll_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/sharehp/css/font-awesome.min.css" rel="stylesheet" media="screen">
    <link href="/static/sharehp/css/sharehp.css" rel="stylesheet" media="screen">
</head>
<body>
{% include "header.htm" %}
<!-- 内容区 -->
<div class="container">
    <div class="row">
        <!-- 左边资源 -->
        <div class="span8">
            <div class="background-wall clearfix">
                <!-- 作者-->
                <div class="detail-res-author">
                    <a href="#"><img class="img-circle" style="width:36px; height:36px"
                                     src="{{ res.avatar.mid|static_url }}"></a>
                    <a href="/user/{{ res.user_id }}/" style="padding-left: 5px;">{{ res.nickname }}</a>
                    <span class="create-time" style="padding-left: 3px;">{{ res.create_date }}</span>

                    <div class="nav-res" id="nav-joke">
                        {% if prev %}
                            <a title="上一条" class="nav-res-last inline-block"
                               href="/detail/{{ res.type }}/{{ res.id }}/prev/"><</a>
                        {% else %}
                            <span class="nav-res-prev-disabled inline-block"><</span>
                        {% endif %}

                        {% if next %}
                            <a title="下一条" class="nav-res-next inline-block"
                               href="/detail/{{ res.type }}/{{ res.id }}/next/">下一条</a>
                        {% else %}
                            <span class="nav-res-next-disabled inline-block">下一条</span>
                        {% endif %}
                    </div>
                </div>
                <!-- 标题 -->
                <div class="detail-res-title">
                    <p class="caption word-break">{{ res.title }}</p>
                </div>
                <!-- 内容 -->
                <div id="detail-{{ res.id }}" class="text-center detail-res-content">
                    {% ifequal  res.type "image" %}
                        <img style="width:{{ res.content.size.0 }}px; height:{{ res.content.size.1 }}px;"
                             src="{{ res.content.url|static_url }}">
                    {% else %}
                        <object width="575" height="440">
                            <param value="{{ res.content.url }}" name="movie">
                            <param value="transparent" name="wmode">
                            <param name="bgcolor" value="#FFFFFF">
                            <embed width="575" height="440" allowscriptaccess="sameDomain" allownetworking="all"
                                   wmode="transparent" allowfullscreen="true"
                                   flashVars="auto_start=off"
                                   type="application/x-shockwave-flash" src="{{ res.content.url }}">
                        </object>
                    {% endifequal %}
                </div>
                <div class="detail-res-footer">
                    {% include "vote_tool_bar.htm" with res=res %}
                    <!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style_24x24 pull-right">
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_weixin"></a>
                        <a class="jiathis_button_renren"></a>
                        <a class="jiathis_button_qzone"></a>
                        <a class="jiathis_button_tqq"></a>
                    </div>
                    <!-- JiaThis Button END -->
                </div>
            </div>
            <br>

            <div class="background-wall">
                <div id="error-msg" class="alert alert-error fade in"
                     style="display: none; padding: 2px 35px 2px 8px; margin-bottom: 12px;">
                </div>
                <div class="control-group clearfix">
                    {% if request.xmanuser.login %}
                        <textarea id="res-comment-content" rows="2" class="btn-block" placeholder="添加评论"></textarea>
                        <button id="submit-res-comment" class="btn btn-primary pull-right" data-loading-text="正在提交"
                                type="button">发布评论
                        </button>
                        <img id="submit-loading" style="display: none" class="pull-right"
                             src="http://sharehp.qiniudn.com/share/mini_loading.gif">
                    {% else %}
                        <textarea id="res-comment-content" rows="2" class="btn-block" readonly="readonly"
                                  placeholder="添加评论"></textarea>
                        <a href="/login/">立即登录</a><span>(登录后才能发表评论)</span>
                        <button id="submit-res-comment" class="btn pull-right" type="button"
                                disabled="disabled">
                            发布评论
                        </button>
                    {% endif %}
                </div>
                <br>

                <div>
                    {% if commentList %}
                        <span style="color: #aaa">共有{{ res.comments }}条评论</span>
                        <ul class="media-list comments-total">
                            {% for comment in commentList %}
                                <li class="media res-comment-item">
                                    <a class="pull-left" href="#">
                                        <img class="img-circle" style="width:36px; height:36px"
                                             src="{{ comment.avatar.mid|static_url }}">
                                    </a>

                                    <div class="media-body">
                                        <a href="/user/{{ comment.user_id }}/"
                                           style="font-size:12px;">{{ comment.nickname }}</a>
                                        <span class="create-time"
                                              style="font-size:12px;padding-left: 3px;">{{ comment.create_date }}</span>

                                        <p class="word-break"> {{ comment.content|white_space|linebreaksbr }} </p>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>还没有人评论哦!</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="span4">
            {% include 'resource_sidebar.htm' %}
        </div>
    </div>
</div>
<br>
{% include 'footer.htm' %}

<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="http://v3.jiathis.com/code/jia.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/sharehp/js/jquery.scrollUp.min.js"></script>
<script src="/static/sharehp/js/common.js"></script>
<script src="/static/sharehp/js/detail.js"></script>
<script>
    var jiathis_config = {
        summary: "{{ res.title }}",
        pic: "{{ res.thumbnail.url|static_url }}"
    }
</script>
</body>
</html>

sharehp/templates/footer.htm
<footer class="footer">
    <div class="container">
        <p class="pull-right"><a href="#" target="_self">回到顶部</a></p>
        <p>Powered by Django © 2014 </p>
    </div>
</footer>

sharehp/templates/group.htm
{% load poll_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/sharehp/css/sharehp.css" rel="stylesheet">
</head>
<body>
{% include "header.htm" %}
<!-- 内容区 -->
<div class="container">
    <div class="row ">
        <div class="span8">
            <div class="background-wall">
                <ul class="breadcrumb clearfix">
                    <!-- FIXME highlight -->
                    <li class="active">
                        最新发布
                        <span class="divider">/<span>
                    </li>
                    <li class="pull-right">
                        <a href="/group/{{ group.id }}/new_topic/">
                            <span class="btn btn-success btn-small ">我要发帖</span>
                        </a>
                    </li>
                </ul>

                {% for topic in topics %}
                    <div class="media topic-sep">
                        <a class="pull-left" href="#">
                            <img class="img-circle" style="width:36px; height:36px" src="{{ topic.avatar.mid|static_url}}">
                        </a>

                        <div class="media-body">
                            <div class="clearfix">
                                <a href="/user/{{ topic.user_id }}/">{{ topic.nickname }}</a>
                                <span class="create-time"> {{ topic.publish_date }}发布 </span>
                                <span class="pull-right label">{{ topic.comments }} 回复</span>
                            </div>
                            <div class="topic-name word-break">
                                <a href="/group/topic/{{ topic.id }}/"><h5>{{ topic.topic_name }}</h5>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div id="pagination"></div>
        </div>

        <div class="span4">
            {% include 'group_sidebar.htm' %}
        </div>
    </div>
</div>
<br>

<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="/static/sharehp/js/bootstrap-paginator.js"></script>
<script src="/static/sharehp/js/jquery.scrollUp.min.js"></script>
<script src="/static/sharehp/js/common.js"></script>
<script type="text/javascript">
    initPaginator({{curPage}}, {{pages}}, "{{ pageUrl }}")
</script>

</body>
</html>

sharehp/templates/group_sidebar.htm
{% load poll_extras %}
<div class="background-wall">
    <div class="clearfix">
        <a href="/group/{{ group.id }}">
            <img class="img-rounded pull-left" style="width:75px; height:75px" src="{{ group.avatar.big|static_url }}">
        </a>
        <div style="display: inline-block; margin-left: 15px;">
            <h5>{{ group.group_name }}</h5>
            <p style="font-size: 12px;">创建时间: {{ group.create_date}}</p>
        </div>
    </div>
    <p class="caption" style="margin-top:15px; color: #999;">{{ group.group_desc }}</p>
</div>

sharehp/templates/header.htm
<!-- 导航栏 -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner ">
        <div class="container">
            <ul class="nav pull-right">
                {% if request.xmanuser.login %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            {{ request.xmanuser.nickname }}
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/account/change_avatar/">帐号设置</a></li>
                            <li class="divider"></li>
                            <li><a href="/loginout/">退出</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}
            </ul>
            <ul class="nav  nav-stacked">
                <li><a href="/index/">最新内容</a></li>
                <li><a href="/tag/video/">搞笑视频</a></li>
                <li><a href="/tag/image/">搞笑图片</a></li>
                <li><a href="/groups/">小组</a></li>
            </ul>
        </div>
    </div>
</div>

<header class="jumbotron subhead">
    <div class="container ">
        <div class="row">
            <div class="span9">
                <h2>不正常人类研究中心
                    <small>精神病人思维广，弱智儿童欢乐多</small>
                </h2>
            </div>
            <div class="span3">
                <a href="/new_resource/" class="btn btn-primary btn-large" style="margin-top: 5px;">逗一个</a>
            </div>
        </div>
    </div>
</header>
<br>

sharehp/templates/index.htm
{% load poll_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/sharehp/css/sharehp.css" rel="stylesheet">
</head>
<body>
{% include "header.htm" %}
<!-- 内容区 -->
<div class="container clearfix">
    {% for resList in resListArray %}
        <div class="waterfall-span pull-left">
            {% for res in resList %}
                <div class="waterfall-wall">
                    <div style="position:relative;">
                        <a href="/detail/{{ res.type }}/{{ res.id }}/" target="_blank">
                            <img style="width:{{ res.thumbnail.size.0 }}px; height:{{ res.thumbnail.size.1 }}px;"
                                 class="img-top-rounded"
                                 src="{{ res.thumbnail.url|static_url }}">
                            {% ifequal res.type "video" %}
                                <span class="play-icon"></span>
                            {% endifequal %}
                        </a>
                    </div>

                    <p class="waterfall-title word-break">{{ res.title }}</p>

                    <div class="waterfall-bottom clearfix">
                        <span class="create-time">{{ res.create_date }}</span>
                        <a class="pull-right" href="/detail/{{ res.type }}/{{ res.id }}/"
                           target="_blank">评论({{ res.comments }})</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>

{% include 'footer.htm' %}

<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="/static/sharehp/js/jquery.scrollUp.min.js"></script>
<script src="/static/sharehp/js/common.js"></script>
</body>
</html>


sharehp/templates/login.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/sharehp/css/sharehp.css" rel="stylesheet" media="screen">
</head>

<body>
<!-- 导航栏 -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner ">
        <div class="container">
            <ul class="nav  nav-stacked">
                <li><a href="/index/">最新内容</a></li>
                <li><a href="/tag/video/">搞笑视频</a></li>
                <li><a href="/tag/image/">搞笑图片</a></li>
                <li><a href="/groups/">小组</a></li>
            </ul>
        </div>
    </div>
</div>

<header class="jumbotron subhead">
    <div class="container">
        <h2 class="text-center">不正常人类研究中心</h2>
    </div>
</header>

<br>

<div class="container">
    <div class="form-signin-register">
        <form action="{{ login_action_url }}" method="post">
            <div class="form-title">
                <h4>登陆帐号</h4>
            </div>
            <span class="error">{{ form.non_field_errors }}</span>
            <span class="error">{{ form.email.errors }}</span>
            <input id="id_email" name="email" type="text" class="input-block-level" placeholder="邮箱"
                   value="{{ form.email.value }}">
            <span class="error">{{ form.password.errors }}</span>
            <input id="id_password" name="password" type="password" class="input-block-level" placeholder="密码"
                   value="{{ form.password.value }}">
            <button class="btn input-block-level btn-primary" type="submit">登陆</button>
        </form>
        <a href="/register/">没有帐号？立即注册</a>
    </div>
</div>

<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</body>
</html>


sharehp/templates/register.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/sharehp/css/sharehp.css" rel="stylesheet" media="screen">
</head>

<body>
<!-- 导航栏 -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner ">
        <div class="container">
            <ul class="nav  nav-stacked">
                <li><a href="/index/">最新内容</a></li>
                <li><a href="/tag/video/">搞笑视频</a></li>
                <li><a href="/tag/image/">搞笑图片</a></li>
                <li><a href="/groups/">小组</a></li>
            </ul>
        </div>
    </div>
</div>

<header class="jumbotron subhead">
    <div class="container">
        <h2 class="text-center">不正常人类研究中心</h2>
    </div>
</header>

<br>

<div class="container">
    <div class="form-signin-register">
        <form action="{{ register_action_url }}" method="post">
            <div class="form-title">
                <h4>注册帐号</h4>
            </div>
            <span class="error">{{ form.email.errors }}</span>
            <input id="id_email" name="email" type="text" class="input-block-level" placeholder="邮箱"
                   value="{{ form.email.value }}">
            <span class="error">{{ form.nickname.errors }}</span>
            <input id="id_nickname" name="nickname" type="text" class="input-block-level" placeholder="昵称（4-16个中英文字符）"
                   value="{{ form.nickname.value }}">
            <span class="error">{{ form.password.errors }}</span>
            <input id="id_password" name="password" type="password" class="input-block-level" placeholder="密码（6-16位）"
                   value="{{ form.password.value }}">
            <button class="btn input-block-level btn-primary" type="submit">注册</button>
        </form>
        <a href="/login/">已经有帐号？立即登录</a>
    </div>
</div>

<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</body>
</html>


sharehp/templates/vote_tool_bar.htm
{% ifequal res.vote_type "up" %}
    <a id="up-{{ res.id }}" href="###" class="btn-icon vote-up vote-enabled ">
        <i class="icon-hand-up icon-large"></i>
        <span>{{ res.up }}</span>
    </a>
    <a id="down-{{ res.id }}" href="###" class="btn-icon vote-down vote-disabled">
        <i class="icon-hand-down icon-large"></i>
        <span>{{ res.down }}</span>
    </a>
    {% else %}{% ifequal res.vote_type "down" %}
        <a id="up-{{ res.id }}" href="###" class="btn-icon vote-up vote-disabled">
            <i class="icon-hand-up icon-large"></i>
            <span>{{ res.up }}</span>
        </a>
        <a id="down-{{ res.id }}" href="###" class="btn-icon vote-down vote-enabled">
            <i class="icon-hand-down icon-large"></i>
            <span>{{ res.down }}</span>
        </a>
    {% else %}
        <a id="up-{{ res.id }}" href="###" class="btn-icon vote-up">
            <i class="icon-hand-up icon-large"></i>
            <span>{{ res.up }}</span>
        </a>
        <a id="down-{{ res.id }}" href="###" class="btn-icon vote-down">
            <i class="icon-hand-down icon-large"></i>
            <span>{{ res.down }}</span>
        </a>
    {% endifequal %}{% endifequal %}